FROM node:latest

ARG ARG_NAME

ENV NAME ${ARG_NAME}

RUN apt-get update

RUN apt-get install -y vim

WORKDIR /usr/src/app/

COPY start.sh .

RUN echo "hello $NAME" > test.txt

# The execute command while run docker
# CMD ["cat", "test.txt"]
CMD ["sh", "start.sh"]
# CMD ["sh", "-c", "tail -f /dev/null"]
